#!/bin/sh

parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

parse_git_dirty () {
 if [[ $((git status 2> /dev/null) | tail -n1) = "" ]]; then
   echo ""
 elif [[ $((git status 2> /dev/null) | tail -n1) != "nothing to commit, working directory clean" ]]; then
   echo " ✗"
 else
   echo ""
 fi
}

LIGHT_CYAN="\[\033[1;36m\]"
YELLOW="\[\033[1;33m\]"
LIGHT_RED="\[\033[1;31m\]"
WHITE="\[\033[1;37m\]"
RESET="\[\033[0m\]"

# Set up things so bash history remembers across terminals
# http://lpetr.org/blog/archives/preserve-bash-history
export HISTSIZE=50000
export HISTFILESIZE=50000
export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

export PS1="$LIGHT_CYAN\u@\h:$YELLOW\w $LIGHT_RED\$(parse_git_branch)$(parse_git_dirty)$YELLOW\n] $RESET"
